# Generated by Django 5.2.13 on 2026-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0010_remove_palco_acessibilidade_mobilidade_reduzida"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concerto",
            options={"ordering": ["hora"]},
        ),
        migrations.AlterModelOptions(
            name="dia",
            options={"ordering": ["data"]},
        ),
        migrations.AlterUniqueTogether(
            name="concerto",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="dia",
            name="cor",
        ),
        migrations.AddField(
            model_name="palco",
            name="acessibilidade_mobilidade_reduzida",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="palco",
            name="capacidade",
            field=models.IntegerField(default=0),
        ),
    ]
